services:
  firebase:
    build: ./firebase
    # If you want to access the emulator ui from outside of Docker, you can uncomment the following lines to expose the ports.
    # ports:
    #   - "4000:4000"
    volumes:
      - ./firebase:/firebase
  workspace:
    command: sleep infinity
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase:8080
    image: debian:trixie
    volumes:
      - .:/workspaces/bouzuya-firestore-client:cached
      - ~/.claude:/home/vscode/.claude
      - ~/.copilot:/home/vscode/.copilot
