name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo +nightly fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    env:
      FIRESTORE_EMULATOR_HOST: localhost:8080
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - run: docker compose up --detach
      - run: docker compose run --rm workspace /bin/bash -c 'until curl --fail --silent http://firebase:8080/; do sleep 1; done'
      - run: docker compose run --rm workspace /bin/bash -c 'cd /workspaces/bouzuya-firestore-client && cargo test'
      - if: always()
        run: docker compose down --volumes
